name: Smartdns Rules
on:
  schedule:
    - cron: 0 20 * * *
  #push:
  #  branches:
  #    - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: |
          mkdir publish
          echo "RELEASE_NAME=Released on $(date -d "8 hour" -u +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "CUSTOM_DIRECT=https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt" >> $GITHUB_ENV
          echo "CUSTOM_PROXY=https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/proxy-list.txt" >> $GITHUB_ENV

      - name: Get file
        run: |
          curl -sSL ${CUSTOM_DIRECT} -o direct.txt
          curl -sSL ${CUSTOM_PROXY} -o proxy.txt

      - name: Transform for Smartdns
        run: |
          sed 's#full:#-.#' direct.txt   > temp-direct.txt
          sed '/^regexp:/d' temp-direct.txt  > ./publish/direct.txt
          sed 's#full:#-.#' proxy.txt > temp-proxy.txt
          sed '/^regexp:/d' temp-proxy.txt  > ./publish/proxy.txt

      - name: Upload To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: list
          path: |
            *
      - name: Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          name: SmartDNS
          body: ${{ env.RELEASE_NAME }}
          tag: smartdns
          makeLatest: false
          allowUpdates: true
          removeArtifacts: true
          artifacts: |
            publish/*.txt
